spring.application.name=camel-microservice-a
server.port=8081

#=================activemq properties==============
spring.activemq.broker-url=tcp://localhost:61616
#=======================================================

#==============Kafka properties===================
camel.component.kafka.brokers=localhost:9092


